<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this Image?' => '¿Seguro que quieres borrar esta imagen?',
    'Blog' => '',
    'Blog Post created successfully' => 'Entrada creada correctamente',
    'Error' => '',
    'Image deleted Successfully' => 'Imagen borrada correctamente',
    'Posts' => 'Entradas',
    'Add Blog Posts' => 'Agregar Entradas',
    'Add Content' => 'Agregar Contenido',
    'Add Images' => 'Agregar Imágenes',
    'Add New Block' => 'Nuevo Bloque',
    'Add New Blog Category' => 'Agregar nueva Categoría',
    'Add New Configuration' => 'Nueva Configuración',
    'Add New Gallery' => 'Nueva Galería',
    'Add New Page' => 'Nueva Página',
    'Add Pages' => 'Agregar Páginas',
    'All' => 'Todos',
    'Block' => 'Bloque',
    'Blog Categories' => 'Categorías del Blog',
    'Blog Category' => 'Categoría',
    'Blog Post' => 'Entrada',
    'Blog Post updated successfully' => 'La Entrada se ha actualizado correctamente',
    'Blog Posts' => 'Entradas',
    'Categories' => 'Categorías',
    'Configuration updated successfully' => 'Configuración actualizada correctamente',
    'Content' => 'Contenido',
    'Create' => 'Crear',
    'Create Block' => 'Crear Bloque',
    'Create Blog Category' => 'Crear Categoría',
    'Create Blog Post' => 'Crear Entrada',
    'Create Configuration' => 'Crear Configuración',
    'Create Gallery' => 'Crear Galería',
    'Create Page' => 'Crear Página',
    'Create great Content' => 'Crea Contenido de calidad',
    'Create your own Pages' => 'Crea tus propias páginas',
    'Edit Your Profile' => 'Edita tu Perfil',
    'Fill Block Data' => 'Rellena los datos del Bloque',
    'Fill Blog Category Data' => 'Rellena los datos de la Categoría',
    'Fill Blog Post Data' => 'Rellena los datos de la Entrada',
    'Fill Configuration Data' => 'Rellena los datos de Configuración',
    'Fill Gallery Data' => 'Rellena los datos de la Galería',
    'Fill Page Data' => 'Rellena los datos de la Página',
    'Galleries' => 'Galerías',
    'Global Configuration' => 'Configuración Global',
    'Great to see you again!' => '¡Es Genial verte de nuevo!',
    'Image Galleries' => 'Galerías de Imágenes',
    'Incorrect username or password.' => 'Nombre de usuario o contraseña incorrectos',
    'Menu' => 'Menú',
    'Message Translations' => 'Traducciones del Mensaje ',
    'New Configuration created successfully' => 'Nueva Configuración creada satisfactoriamente',
    'New Post' => 'Nueva Entrada',
    'Page' => 'Páginas',
    'Pages' => 'Páginas',
    'Profile' => 'Perfil',
    'Profile updated successfully' => 'Perfil actualizado satisfactoriamente',
    'Save' => 'Guardar',
    'Saved' => 'Guardado',
    'Sign in' => 'Ingresar',
    'Sign in to start your session' => 'Haz Log-in para iniciar sesión',
    'Sign out' => 'Salir',
    'Step 1' => 'Paso 1',
    'Step 2' => 'Paso 2',
    'Step 3' => 'Paso 3',
    'Step 4' => 'Paso 4',
    'The requested page does not exist.' => 'La página requerida no existe',
    'There was some error uploading the blog post Image' => 'Ha habido un error al subir la Imagen de la Entrada',
    'There was some error uploading your avatar Image' => 'Ha habido un error al subir la imagen de tu Avatar',
    'Translate UI' => 'Traducir Interfaz Usuario',
    'Update Block' => 'Actualizar Bloque',
    'Update Blog Category' => 'Actualizar Categoría',
    'Update Blog Post' => 'Actualizar Entrada',
    'Update Configuration' => 'Actualizar Configuración',
    'Update Gallery' => 'Actualizar Galería',
    'Update Page' => 'Actualizar Página',
    'Upload Images' => 'Subir Imágenes',
    'Upload awesome Images' => 'Sube Imágenes llamativas',
    'User Profile' => 'Perfil de Usuario',
    'Welcome to HeavyCMS' => 'Bienvenid@ a HeavyCMS',
    'Write interesting Blog Posts' => 'Escribe Entradas interesantes',
    'easy, fast, flexible' => 'fácil, rápido, flexible',
];
