<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add New Blog Post' => 'Nuevo Blog Post',
    'Add New Configuration' => 'Nueva Configuración',
    'Add New Content' => 'Nuevo Contenido',
    'Add New Gallery' => 'Nueva Galería',
    'Add New Page' => 'Nueva Página',
    'All' => 'Todos',
    'Avatar' => '',
    'Blog' => '',
    'Blog Posts' => '',
    'BlogPost updated successfully' => 'Blog Post actualizado correctamente',
    'Configuration updated successfully' => 'Configuración actualizada correctamente',
    'Content' => 'Contenido',
    'Contents' => 'Contenidos',
    'Create' => 'Crear',
    'Create Blog Post' => 'Crear Blog Post',
    'Create Configuration' => 'Crear Configuración',
    'Create Content' => 'Crear Contenido',
    'Create Gallery' => 'Crear Galería',
    'Create Page' => 'Crear Página',
    'Edit Your Profile' => 'Edita tu Perfil',
    'Error saving translation' => 'Error al guardar las traducciones',
    'Fill Blog Post Data' => 'Rellena los datos del Blog Post',
    'Fill Configuration Data' => 'Rellena los datos de Configuración',
    'Fill Content Data' => 'Rellena los datos del Contenido',
    'Fill Gallery Data' => 'Rellena los datos de la Galería',
    'Fill Page Data' => 'Rellena los datos de la Página',
    'Galleries' => 'Galerías',
    'Global Configuration' => 'Configuración Global',
    'Image Galleries' => 'Galerías de Imágenes',
    'Menu' => 'Menú',
    'Message Translations' => 'Traducciones del Mensaje ',
    'New Blog Post created successfully' => 'Nuevo Blog Post creado satisfactoriamente',
    'New Configuration created successfully' => 'Nueva Configuración creada satisfactoriamente',
    'Pages' => 'Páginas',
    'Profile' => 'Perfil',
    'Profile updated successfully' => 'Perfil actualizado satisfactoriamente',
    'Save' => 'Guardar',
    'Sign in to start your session' => 'Haz Log-in para iniciar sesión',
    'The requested page does not exist.' => 'La página requerida no existe',
    'There was some error uploading your avatar Image' => 'Ha habido un error al subir la imagen de tu Avatar',
    'Translate UI' => 'Traducir Interfaz Usuario',
    'Translations saved successfully' => 'Traducciones guardadas satisfactoriamente',
    'Update Blog Post' => 'Actualizar ',
    'Update Configuration' => 'Actualizar Configuración',
    'Update Content' => 'Actualizar Contenido',
    'Update Gallery' => 'Actualizar Galería',
    'Update Page' => 'Actualizar Página',
    'Upload Images' => 'Subir Imágenes',
    'User Profile' => 'Perfil de Usuario',
];
