<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All' => '',
    'Auth Key' => '',
    'Avatar' => '',
    'Blog Posts' => '',
    'Category' => '',
    'Configuration updated successfully' => '',
    'Contents' => '',
    'Create Blog Post' => '',
    'Create Configuration' => '',
    'Create Content' => '',
    'Create Page' => '',
    'Created At' => '',
    'Created By' => '',
    'Email' => '',
    'Error saving translation' => '',
    'File Name' => '',
    'Gallery ID' => '',
    'Global Configuration' => '',
    'ID' => '',
    'Is Active' => '',
    'Language' => '',
    'Lastname' => '',
    'Message Translations' => '',
    'Name' => '',
    'New Configuration created successfully' => '',
    'Pages' => '',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Profile' => '',
    'Profile updated successfully' => '',
    'Save' => '',
    'Sign in to start your session' => '',
    'Slug' => '',
    'Sort Order' => '',
    'Source Message' => '',
    'Status' => '',
    'There was some error uploading your avatar Image' => '',
    'Translation' => '',
    'Translations saved successfully' => '',
    'Update Blog Post' => '',
    'Update Configuration' => '',
    'Update Content' => '',
    'Update Page' => '',
    'Updated Ad' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Upload Images' => '',
    'User ID' => '',
    'Username' => '',
];
