<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Anchor' => '',
    'Avatar' => '',
    'Blog Category' => 'Categoría',
    'Blog Post' => 'Post',
    'Email' => '',
    'ID' => '',
    'Meta Description' => '',
    'Password Hash' => '',
    'Slug' => '',
    'Url' => '',
    'Auth Key' => 'Clave de Autorización',
    'Category' => 'Categoría',
    'Content ID' => 'Contenido ID',
    'Created At' => 'Creado en',
    'Created By' => 'Creado por',
    'Description' => 'Descripción',
    'Featured Image' => 'Imagen Destacada',
    'File Name' => 'Nombre del Fichero',
    'Flat Page ID' => 'Página ID',
    'Gallery ID' => 'Galería ID',
    'Identifier' => 'Identificador',
    'Is Active' => 'Está Activo',
    'Is Published' => 'Está Publicado',
    'Language' => 'Idioma',
    'Lastname' => 'Apellido',
    'Name' => 'Nombre',
    'Password Reset Token' => 'Token de Reseteo de Password',
    'Sort Order' => 'Posición',
    'Source Message' => 'Mensaje Origen',
    'Status' => 'Estado',
    'Text' => 'Texto',
    'Title' => 'Título',
    'Translation' => 'Traducción',
    'Updated At' => 'Actualizado en',
    'Updated By' => 'Actualizado por',
    'User ID' => 'Usuario ID',
    'Username' => 'Nombre de Usuario',
    'Value' => 'Valor',
];
